import { sha256 } from "../utils/checksum.js";
import type { VisionConfig } from "../types/config.js";

export function wrapGeneratedContent(config: VisionConfig, body: string, schemaChecksum: string): string {
  const start = config.safety.generatedMarkers.start;
  const end = config.safety.generatedMarkers.end;
  const lineEnding = config.formatting.lineEnding;
  const normalizedBody = body.trim();
  const contentChecksum = sha256(normalizedBody);
  const lines = [
    "/* eslint-disable */",
    "// This file was generated by vision-sync.",
    "// Do not edit this file manually. Change the schema or generator config instead.",
    `// @vision-schema-checksum ${schemaChecksum}`,
    `// @vision-content-checksum ${contentChecksum}`,
    `// ${start}`,
    normalizedBody,
    `// ${end}`
  ];

  return `${lines.join(lineEnding)}${config.formatting.finalNewline ? lineEnding : ""}`;
}

export function isVisionGenerated(content: string, config: VisionConfig): boolean {
  return content.includes(config.safety.generatedMarkers.start) && content.includes(config.safety.generatedMarkers.end);
}
